--- #YAML:1.0
name: Math-Symbolic
version: 0.122
abstract: Symbolic calculations
license: perl
distribution_type: module
requires:
  Test::More: 0.44
  Data::Dumper: 0
recommends:
  Parse::RecDescent: 0
build_requires:
  Parse::RecDescent: 0
dynamic_config: 0
