# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Symbolic
version:      0.160
version_from: lib/Math/Symbolic.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    Memoize:                       1.01
    Parse::RecDescent:             0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
